services:
  web:
    build:
      context: ./url_shortner/
      dockerfile: Dockerfile
    command: gunicorn url_shortner.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8090
    ports:
      - 8090:8090
    depends_on:
      - mongo_db
      - mongo2

  mongo_db:
    image: mongo:7.0
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - 27017:27017
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    volumes:
      - "./db_data/mongo_db_data:/data/db"
      - "./db_data/mongo_db_config:/data/configdb"
  
  mongo2:
    image: mongo:7.0
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27018"]
    ports:
      - 27018:27018
    volumes:
      - "./db_data/mongo2_data:/data/db"
      - "./db_data/mongo2_config:/data/configdb"

volumes:
  mongo_db_data:
  mongo_db_config:
  mongo2_data:
  mongo2_config:

