apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      role: mongo
  serviceName: \"mongo\"
  replicas: 3
  template:
    metadata:
      labels:
        role: mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        command: [\"mongod\"]
        args: [\"--replSet\", \"rs0\", \"--bind_ip\", \"0.0.0.0\"]
        ports:
        - containerPort: 27017